version: "3.1"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server
    command: sleep infinity
    volumes:
      - ./:/aplicacao
    ports:
      - 8080:8080
    networks:
      - mynetwork
      
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana/:/var/lib/grafana/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Senha do admin (mude para algo seguro)
      - GF_SECURITY_ADMIN_USER=admin      # Usuário admin (mude se necessário)    
    ports:
      - 3000:3000
    networks:
      - mynetwork


networks:
  mynetwork: